openapi: 3.0.0
info:
  title: Teste para Regulação
  description: Documentação simples dos endpoints
  contact:
    email: teste@bridge.ufsc.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
  x-logo:
    url: https://www.ufrgs.br/telessauders/wp-content/uploads/2016/03/519_e-SUS_279J_original.png
    backgroundColor: '#FFFFFF'
    altText: e-SUS Logo
    href: https://integracao.esusab.ufsc.br/
servers:
- url: https://virtserver.swaggerhub.com/nathanwerlich/Teste/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Post PEC
  description: Padrão de POST do PEC
paths:
  /solicitacao:
    post:
      tags:
      - Post que o PEC realiza
      summary: Adiciona uma solicitação
      description: Envia uma requisição para o orgão regulador
      operationId: addSolicitacao
      requestBody:
        description: Dados da solicitação
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dadosSolicitacao'
      responses:
        "201":
          description: Solicitação recebida
        "400":
          description: Input ou objeto invalido
        "409":
          description: Já existe uma solicitação identica
  /especialidades:
    post:
      tags:
      - Formato do POST que o PEC aceita
      summary: Recebe especialidades
      description: Busca as especialidades
      operationId: getEspecialidade
      requestBody:
        description: Dados das especialidades
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dadosEspecialidade'
      responses:
        "201":
          description: Especialidades atualizadas
        "400":
          description: Não foi possivel atualizar as especialidades
        "501":
          description: Servidor indisponivel
components:
  schemas:
    dadosSolicitacao:
      required:
      - classificacaoRisco
      - cnsCidadao
      - dataEncaminhamento
      - especialidade
      - token
      type: object
      properties:
        token:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        especialidade:
          type: string
          example: acupunturista
        classificacaoRisco:
          type: string
          example: Emergência
        telefone:
          type: string
          format: string
          example: 48 9 98855-4433
        cnsCidadao:
          type: string
          example: "155929702510002"
        dataEncaminhamento:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    dadosEspecialidade:
      required:
      - id
      - nome
      type: object
      properties:
        id:
          type: number
          format: ID
          example: 123
        nome:
          type: string
          example: CONSULTA EM CIRURGIA ONCOLÓGICA
